### ISSUE TITLE
Problem about pretrain model

### ISSUE THREAD

**Issue by Greatxcw** [guoweiyu/Context-Enhanced-Stereo-Transformer#6]
Hi, Thanks a lot for your great work. I wanted to retrain your model, but I encountered the following problem：
Epoch: 0
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "main.py", line 246, in <module>
    main(args_)
  File "main.py", line 216, in main
    train_one_epoch(model, data_loader_train, optimizer, criterion, device, epoch, summary_writer,
  File "/data/CEST/Context-Enhanced-Stereo-Transformer-master/utilities/train.py", line 63, in train_one_epoch
    train_stats['px_error_rate'] = train_stats['error_px'] / train_stats['total_px']
ZeroDivisionError: float division by zero

I don't know how to solve this problem. I hope you can take a look and take up your valuable time.

**Comment by Greatxcw** [comment]
The reason for this problem is that my dataset format is incorrect. Thank you again for your excellent work！
